# Generated by Django 3.1.1 on 2021-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210324_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
