# Generated by Django 3.1.1 on 2021-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210325_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(related_name='_blog_like_+', to='blog.Blog_user'),
        ),
    ]
