# Generated by Django 3.1.1 on 2021-03-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210325_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='comment',
        ),
    ]
