# Generated by Django 3.1.1 on 2021-03-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210325_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blog_like_+', to='blog.Blog_user'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
